########################
# Prompt customization #
########################
# https://github.com/bhilburn/powerlevel9k
#ZSH_THEME="powerlevel10k/powerlevel10k"
#POWERLEVEL9K_MODE="awesome-patched"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(user dir_writable dir rbenv vcs)
POWERLEVEL9K_RIGHT_ROMPT_ELEMENTS=(status root_indicator background_jobs history time virtualenv)

export DEFAULT_USER=nmaupu

###########
# History #
###########
export HISTFILE=/Users/nicolas_maupu/.zsh_history
export HISTSIZE=50000
export SAVEHIST=50000
setopt EXTENDED_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS

#############
# Some vars #
#############
export TERM=xterm-256color
export GIT_EDITOR=nvim
export EDITOR=nvim
export GOROOT=/usr/local/go
export GOPATH=$HOME/work/go
export ANSIBLE_NOCOWS=1
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
export DOCKER_ID_USER=nmaupu
#https://wiki.archlinux.org/index.php/Xmonad#LibreOffice_-_focus_flicking_between_main_window_and_dialog
export SAL_USE_VCLPLUGIN=gen lowriter
export JAVA_HOME=/opt/jdk
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$HOME/bin:/opt/bin:${JAVA_HOME}/bin
export VAULT_CACERT=~/.config/vault-ca.pem

# Do not sighup background jobs
setopt NO_HUP
setopt NO_CHECK_JOBS

# Enable bash comment style with dash character
setopt interactivecomments

#################
# Misc bindings #
#################
bindkey "^[Oc" forward-word
bindkey "^[Od" backward-word
bindkey "\^U"  backward-kill-line
#bindkey "^[m"  copy-earlier-word

if [ -f ~/.ssh/config ]; then
  h=()
  h=($h ${${${(@M)${(f)"$(cat ~/.ssh/config*)"}:#Host *}#Host }:#*[*? ]*})
  if [[ $#h -gt 0 ]]; then
    zstyle ':completion:*:ssh:*' hosts $h
    zstyle ':completion:*:scp:*' hosts $h
    zstyle ':completion:*:rsync:*' hosts $h
    zstyle ':completion:*:slogin:*' hosts $h
    zstyle ':completion:*:pssh:*' hosts $h
    zstyle ':completion:*:cssh:*' hosts $h
  fi
fi

#####################
# plugins and theme #
#####################
source "${HOME}/.antigen.zsh"

antigen use oh-my-zsh
antigen bundle common-aliases
antigen bundle djui/alias-tips
antigen bundle docker
antigen bundle fabric
antigen bundle git
antigen bundle git-extras
antigen bundle git-flow
antigen bundle helm
antigen bundle kubectl
antigen bundle pip
antigen bundle sudo
antigen bundle vagrant
antigen bundle virtualenv
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-syntax-highlighting
antigen theme  bhilburn/powerlevel9k powerlevel9k
antigen apply

###############################
# Misc at the end of the file #
###############################
# FZF
_gen_fzf_default_opts() {
  local base03="234"
  local base02="235"
  local base01="240"
  local base00="241"
  local base0="244"
  local base1="245"
  local base2="254"
  local base3="230"
  local yellow="136"
  local orange="166"
  local red="160"
  local magenta="125"
  local violet="61"
  local blue="33"
  local cyan="37"
  local green="64"

  # Solarized Dark color scheme for fzf
  export FZF_DEFAULT_OPTS="
    --no-height --border --exact
    --color fg:-1,bg:-1,hl:$blue,fg+:$base2,bg+:$base02,hl+:$blue
    --color info:$yellow,prompt:$yellow,pointer:$base3,marker:$base3,spinner:$yellow
  "

}
_gen_fzf_default_opts
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Custom aliases
alias test_term_colors="wget -O - https://raw.githubusercontent.com/robertknight/konsole/master/tests/color-spaces.pl | perl; \
  curl -s https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh | bash"

export DOCKER_ID_USER=nmaupu
alias history="fc -il 1"
alias vim="nvim"
alias vi="nvim"
# ~/.dircolors/themefile
eval $(gdircolors ~/.dircolors/dircolors.256dark)

# Aliases
alias ls='gls --color=auto'
alias ll='ls -al'

# Kubernetes - change context
kcs() {
  local new_context
  if [ "$1" = '-' ]; then
    new_context = '-'
  else
    new_context=$(kubectl config get-contexts -o=name | fzf -0 -1 --tac -q "${1:-""}")
  fi

  kubectl config use-context "${new_context}"
}

# Kubernetes - change current namespace
kns() {
  local new_context
  if [ "$1" = '-' ]; then
    new_ns = '-'
  else
    new_ns=$(kubectl get ns -o json | jq -r '.items[].metadata.name' | fzf -0 -1 --tac)
  fi

  kubectl config set-context $(kubectl config current-context) --namespace="${new_ns}"
}

autocomplete_kubectl() {
  source <(kubectl completion zsh)
}

# Helm completion
autocomplete_helm() {
  source <(helm completion zsh)
}

# Vault completion
autocomplete_vault() {
  autoload -U +X bashcompinit && bashcompinit
  complete -o nospace -C /usr/local/bin/vault vault
}

# Custom and private configs
if [ -d "${HOME}/.zshrc.d" ]; then
  find "${HOME}/.zshrc.d" -type f | while read -r file; do
    source ${file}
  done
fi

# Trying to fix problem with autocompletion commands
# https://github.com/zsh-users/antigen/issues/583#issuecomment-336903466
# source $HOME/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh

# Iterm2 integration related functions
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
function iterm2_print_user_vars () {
  KUBECONTEXT=$(CTX=$(kubectl config current-context) 2> /dev/null;if [ $? -eq 0 ]; then echo "\u2638 $CTX";fi)
  KUBENAMESPACE=$(NS=$(kubectl config view --minify -o=jsonpath={..namespace}) 2> /dev/null; if [ $? -eq 0 ]; then echo "$NS"; fi)
  iterm2_set_user_var kubeContext "$KUBECONTEXT ($KUBENAMESPACE)"
}

# added by travis gem
[ -f /Users/nicolas_maupu/.travis/travis.sh ] && source /Users/nicolas_maupu/.travis/travis.sh
